--
-- Database: `notebook`
--
CREATE DATABASE IF NOT EXISTS `NOTEBOOK` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `NOTEBOOK`;

--
-- create TABLES
--

-- Table stores all professors
CREATE TABLE IF NOT EXISTS `PROFESSOR` (
  `PROFESSOR_ID` int(11) AUTO_INCREMENT NOT NULL,
  `PROFESSOR_FNAME` varchar(100) NOT NULL,
  `PROFESSOR_LNAME` varchar(100) NOT NULL,
  PRIMARY KEY (`PROFESSOR_ID`)
) ENGINE=InnoDB;

-- Table stores all students
CREATE TABLE IF NOT EXISTS `STUDENT` (
  `STUDENT_ID` int(11) AUTO_INCREMENT NOT NULL,
  `STUDENT_FNAME` varchar(100) NOT NULL,
  `STUDENT_LNAME` varchar(100) NOT NULL,
  `DATE_OF_BIRTH` date NOT NULL,
  `GENDER` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`STUDENT_ID`)
) ENGINE=InnoDB;

-- Table stores all subjects
CREATE TABLE IF NOT EXISTS `SUBJECT` (
  `SUBJECT_ID` int(11) AUTO_INCREMENT NOT NULL,
  `SUBJECT_NAME` varchar(100) NOT NULL,
  `SUBJECT_CODE` varchar(100) NOT NULL,
  `SUBJECT_DESCRITION` varchar(250) NOT NULL,
  PRIMARY KEY (`SUBJECT_ID`)
) ENGINE=InnoDB;

-- Table stores all Semesters
CREATE TABLE IF NOT EXISTS `SEMESTER` (
  `SEMESTER_ID` int(11) AUTO_INCREMENT NOT NULL,
  `SEMESTER_NAME` varchar(100) NOT NULL,
  `SEMESTER_DESCRIPTION` varchar(250) NOT NULL,
  `SEMESTER_SART_DATE`   date NOT NULL,
  `SEMESTER_END_DATE`   date NOT NULL,
  `MAX_SUBJECTS` int(04) NOT NULL,
  PRIMARY KEY (`SEMESTER_ID`)
) ENGINE=InnoDB;

-- Tables store all classes - One "class" is a particular subject taught by a professor for a semester
CREATE TABLE IF NOT EXISTS `CLASS` (
  `CLASS_ID` int(11) AUTO_INCREMENT NOT NULL,
  `SEMESTER_ID` int(11) NOT NULL,
  `SUBJECT_ID` int(11) NOT NULL,
  `PROFESSOR_ID`   int(11) NOT NULL,  
  PRIMARY KEY (`CLASS_ID`)
) ENGINE=InnoDB;

-- Tables stores information on all classes a student has registered for
CREATE TABLE IF NOT EXISTS `STUDENT_CLASS_XREF` (
  `STUDENT_CLASS_XREF_ID` int(11) AUTO_INCREMENT NOT NULL,
  `STUDENT_ID` int(11) NOT NULL,
  `CLASS_ID` int(11) NOT NULL,
PRIMARY KEY (`STUDENT_CLASS_XREF_ID`)
) ENGINE=InnoDB;

-- Table stores notes
CREATE TABLE IF NOT EXISTS `NOTE` (
  `NOTE_ID` int(11) AUTO_INCREMENT NOT NULL,
  `STUDENT_CLASS_XREF_ID` int(11) NOT NULL,
  `TITLE` varchar(50) NOT NULL,
  `DATE` date NOT NULL,
  `TEXT` TEXT NOT NULL,
  PRIMARY KEY (`NOTES_ID`)
) ENGINE=InnoDB;

--
-- add FK constraints
--
ALTER TABLE `CLASS` ADD CONSTRAINT `CLASS_FK1` FOREIGN KEY (`PROFESSOR_ID`)
REFERENCES `professor` (`PROFESSOR_ID`) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE `CLASS` ADD CONSTRAINT `CLASS_FK2` FOREIGN KEY (`SEMESTER_ID`)
REFERENCES `SEMESTER` (`SEMESTER_ID`) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE `CLASS` ADD CONSTRAINT `CLASS_FK3` FOREIGN KEY (`SUBJECT_ID`)
REFERENCES `SUBJECT` (`SUBJECT_ID`) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE `STUDENT_CLASS_XREF` ADD CONSTRAINT `STUDENT_CLASS_FK1` FOREIGN KEY (`STUDENT_ID`)
REFERENCES `STUDENT` (`STUDENT_ID`) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE `STUDENT_CLASS_XREF` ADD CONSTRAINT `STUDENT_CLASS_FK2` FOREIGN KEY (`CLASS_ID`)
REFERENCES `CLASS` (`CLASS_ID`) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE `NOTE` ADD CONSTRAINT `NOTE_FK1` FOREIGN KEY (`STUDENT_CLASS_XREF_ID`)
REFERENCES `STUDENT_CLASS_XREF` (`STUDENT_CLASS_XREF_ID`) ON UPDATE CASCADE ON DELETE CASCADE;
